spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    product-url: http://localhost:8050/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments