server:
  port: 8040

logging:
  level:
    org.springframework: INFO

spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      authentication-database: admin
      database: payment
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.abdul.ecommerce.payment.dto.PaymentConfirmation

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8060/api/v1/payments