server:
  port: 8060

logging:
  level:
    org.springframework: INFO

spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      authentication-database: admin
      database: payment
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.abdul.ecommerce.payment.dto.PaymentConfirmation
application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8060/api/v1/payments